# Generated by Django 5.2.6 on 2025-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualtour',
            options={'verbose_name': 'Virtual Tour', 'verbose_name_plural': 'Virtual Tours'},
        ),
        migrations.RemoveField(
            model_name='virtualtour',
            name='tour_image',
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='iframe_code',
            field=models.TextField(blank=True, help_text='Optional iframe embed code for custom platforms', null=True),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='platform',
            field=models.CharField(choices=[('matterport', 'Matterport'), ('kuula', 'Kuula'), ('cupix', 'Cupix'), ('youtube', 'YouTube 360'), ('custom', 'Custom/Other')], default='matterport', help_text='Select the 3D tour platform', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for the tour', null=True, upload_to='tours/previews/'),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='tour_url',
            field=models.URLField(default='https://example.com/tour', help_text='URL of the 3D tour (e.g., Matterport, Kuula embed link)', max_length=500),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
