# Generated by Django 5.2.6 on 2025-10-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_virtualtour_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list (e.g., WiFi, Parking, Gym, Pool)'),
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date when property becomes available', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit required', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured listing'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('studio', 'Studio'), ('townhouse', 'Townhouse'), ('room', 'Single Room')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, help_text='Property size in square feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('pending', 'Pending')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, help_text='Number of bathrooms (e.g., 1.5, 2.0)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent price', max_digits=10),
        ),
    ]
